module.exports = {
  start: 'START',
  finish: '連署達<%= target %>人',
  person: '人',
  letsClean: `只要每連署多1個人
我就能讓跑道變乾淨！
跟我一起減塑路跑吧！`,
  current: '目前連署人數',
  target: '目標',
  action: '我要連署',
  title: '無拘無塑來跑步',
  sub: '當路跑活動的風潮日益成熟，你想像過最理想的路跑環境，應該具備什麼條件？',
  hope: '我希望未來能擁有更好的路跑環境',
  fullName: '跑者',
  email: 'E-mail',
  phoneNumber: '電話',
  dateOfBirth: '出生年份',
  submit: '送出',
  confirm: '確認',
  thanks: '感謝你的連署！',
  ending: '終點',
  toPetition: '返回',
  share: '支持與分享',
  donate: '捐款支持',
  FB: 'FB分享',
  go: '出發',
  toending: '不是跑步到終點',
  done: 'FINISH',
};
